server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/ms-catalogo
    username: root
    password: # Add your actual database password here
    driver-class-name: com.mysql.cj.jdbc.Driver
  show:
    sql: true
